services:
  backend:
    build: ./backend
    restart: unless-stopped
    networks:
      - app-network
    environment:
      HELLO_TEXT: ${HELLO_TEXT}
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
